/// A single water-intake log line — the domain shape of a
/// `hydration_entries` row.
///
/// `occurredAt`/`createdAt` are rich [DateTime]s (UTC) here, not the
/// epoch-millis the database stores: `LogWater` reads "now" from an
/// injected `Clock`, which returns a `DateTime`, and epoch-millis is a
/// persistence detail this layer shouldn't know about. See
/// `docs/workplans/2026-09-04-hydration-logging.md` § API contract for
/// the underlying schema and `data/models/hydration_entry_mapper.dart`
/// for the db <-> domain conversion.
class HydrationEntry {
  const HydrationEntry({
    required this.id,
    required this.amountMl,
    required this.occurredAt,
    required this.localDate,
    required this.source,
    required this.createdAt,
  });

  /// UUID v4, generated by `LogWater`.
  final String id;

  /// Between 50 and 2,000 (`FR-024`) — enforced by `LogWater` before an
  /// entry is ever created, and mirrored by a `CHECK` constraint on the
  /// table as a second line of defence.
  final int amountMl;

  /// The instant the water was actually consumed, in UTC.
  final DateTime occurredAt;

  /// The local-calendar-date (`'YYYY-MM-DD'`) [occurredAt] falls on, per
  /// `BR-15`/`BR-16`. Stored alongside the instant rather than derived on
  /// read, so a later device timezone change cannot rewrite which day an
  /// existing entry belongs to.
  final String localDate;

  /// Where this entry came from.
  final HydrationSource source;

  /// When this row was written. Mirrors [occurredAt] this pass — nothing
  /// backdates an entry yet (that is what `HydrationSource.imported` is
  /// reserved for).
  final DateTime createdAt;

  HydrationEntry copyWith({
    String? id,
    int? amountMl,
    DateTime? occurredAt,
    String? localDate,
    HydrationSource? source,
    DateTime? createdAt,
  }) {
    return HydrationEntry(
      id: id ?? this.id,
      amountMl: amountMl ?? this.amountMl,
      occurredAt: occurredAt ?? this.occurredAt,
      localDate: localDate ?? this.localDate,
      source: source ?? this.source,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  @override
  bool operator ==(Object other) {
    return other is HydrationEntry &&
        other.id == id &&
        other.amountMl == amountMl &&
        other.occurredAt == occurredAt &&
        other.localDate == localDate &&
        other.source == source &&
        other.createdAt == createdAt;
  }

  @override
  int get hashCode =>
      Object.hash(id, amountMl, occurredAt, localDate, source, createdAt);

  @override
  String toString() =>
      'HydrationEntry(id: $id, amountMl: $amountMl, localDate: $localDate, '
      'source: $source)';
}

/// Where a logged entry came from — `hydration_entries.source`.
///
/// `imported` is reserved for a future backfill/import feature; nothing
/// in this pass writes it, but it is part of the vocabulary now so the
/// mapper's "unknown value" branch has a complete set of known cases to
/// compare against.
enum HydrationSource { quickAdd, custom, imported }
